name: LambdaDeploy

on:
  push:
    branches:
      - wip_lambda_deployment

env:
  AWS_REGION: us-west-2
  LAMBDA_FUNCTION_NAME: gridview-analytics-api-prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm_config_target_arch=x64 npm_config_target_platform=linux npm_config_target_libc=glibc yarn install

      - name: Build package 
        id: build-lambda-package
        env:
          PACKAGE_ID: ${{ github.sha }}
        run: |
          yarn run build
          mkdir package
          cp -r dist/. package
          cp -r node_modules package
          cd package && zip -r ../package-$PACKAGE_ID.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2146 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2146 }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Lambda function
        id: update-lambda-function
        env:
          PACKAGE_ID: ${{ github.sha }}
        run: |
          ls -l
          aws lambda list-functions
          echo "aws lambda update-function-code function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://package-$PACKAGE_ID.zip"
